databases:
  - name: alpha_blog
    databaseName: alpha_blog
    user: alpha_blog
    plan: free

services:
  - type: web
    name: alpha-blog
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alpha_blog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
